(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("alloc_view" . ("kernel-events.info" 5084 291 "Function alloc_view @var{kind}"))
("emit_display" . ("kernel-events.info" 2718 419 "Function emit_display @var{pairs}"))
("emit_done" . ("kernel-events.info" 4698 187 "Function emit_done @var{view_id}[ @var{status}]"))
("emit_frame" . ("kernel-events.info" 3374 190 "Function emit_frame @var{view_id} @var{payload}"))
("emit_log" . ("kernel-events.info" 4274 196 "Function emit_log @var{view_id} @var{level} @var{message}"))
("emit_progress" . ("kernel-events.info" 3817 204 "Function emit_progress @var{view_id} @var{fraction}"))
("kernel_events_available" . ("kernel-events.info" 5522 224 "Function kernel_events_available"))
("show" . ("kernel-events.info" 2203 317 "Function show @var{expr}"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for kernel-events" . ("kernel-events.info" 1624 441))
("Introduction to kernel-events" . ("kernel-events.info" 602 861))
("See also" . ("kernel-events.info" 5861 321))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
