(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("alloc_view" . ("kernel-events.info" 5330 291 "Function alloc_view @var{kind}"))
("emit_capabilities" . ("kernel-events.info" 6232 275 "Function emit_capabilities [@var{packages}]"))
("emit_display" . ("kernel-events.info" 2964 419 "Function emit_display @var{pairs}"))
("emit_done" . ("kernel-events.info" 4944 187 "Function emit_done @var{view_id}[ @var{status}]"))
("emit_error" . ("kernel-events.info" 7437 467 "Function emit_error @var{kind} @var{message}"))
("emit_frame" . ("kernel-events.info" 3620 190 "Function emit_frame @var{view_id} @var{payload}"))
("emit_log" . ("kernel-events.info" 4520 196 "Function emit_log @var{view_id} @var{level} @var{message}"))
("emit_progress" . ("kernel-events.info" 4063 204 "Function emit_progress @var{view_id} @var{fraction}"))
("emit_ready" . ("kernel-events.info" 6702 119 "Function emit_ready"))
("emit_stdin_request" . ("kernel-events.info" 8431 418 "Function emit_stdin_request @var{prompt} @var{kind}"))
("emit_vars" . ("kernel-events.info" 8111 166 "Function emit_vars"))
("kernel_events_available" . ("kernel-events.info" 5820 224 "Function kernel_events_available"))
("show" . ("kernel-events.info" 2449 317 "Function show @var{expr}"))
("start_session" . ("kernel-events.info" 7017 221 "Function start_session [@var{packages}]"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for kernel-events" . ("kernel-events.info" 1624 687))
("Introduction to kernel-events" . ("kernel-events.info" 602 861))
("See also" . ("kernel-events.info" 8960 239))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
